trigger:
  - pipeline-changes

pool:
  vmImage: "ubuntu-latest"

variables:
  TS_NODE_COMPILER_OPTIONS: '{"module": "commonjs"}'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "18.17.1"
    displayName: "Install Node.js"

  - script: |
      npm install
    displayName: "Install dependencies"

  - script: |
      rm -rf ./formatted-content/*
      rm -rf ./out/*
    displayName: "Clean up old files"

  - script: |
      npx ts-node build/createSchoolList.ts
    displayName: "fetch and format list of schools based on state list"

  - script: |
      npx ts-node build/formatContentFiles.ts
    displayName: "format content markdown files"

  - script: |
      npm run build
    displayName: "Build Static Site"

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: "out"
      artifactName: "Website"
      publishLocation: "Container"
