backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "public/uploads" # Where media files will be stored
public_folder: "/uploads" # Where the media files can be accesed from the server
publish_mode: editorial_workflow # For Drafts

collections:
  - name: "sections" # Used in routes, e.g., /admin/collections/blog
    label: "Home Page Section" # Used in the UI
    folder: "content/home-page" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Heading", name: "heading", widget: "string" }
      - { label: "Order", name: "order", widget: "number" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Open on Load", name: "defaultOpen", widget: "boolean" }
  - name: "termsAndConditionsContent" # Used in routes, e.g., /admin/collections/blog
    label: "Terms And Conditions Content" # Used in the UI
    folder: "content/terms-and-conditions" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "formCopy" # Used in routes, e.g., /admin/collections/blog
    label: "Rights Request Form Content" # Used in the UI
    folder: "content/rights-request-form" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "avaliableStates"
    label: "Avaliable States and Actions"
    folder: "content/avaliable-states-and-actions"
    create: true
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "State", name: "state", widget: "string" }
      - {
          label: "Right to Access",
          name: "right_to_access",
          widget: "boolean",
          default: false,
        }
      - {
          label: "Right to Correction",
          name: "right_to_correction",
          widget: "boolean",
          default: false,
        }
      - {
          label: "Right to Deletion",
          name: "right_to_deletion",
          widget: "boolean",
          default: false,
        }
      - {
          label: "Right to opt-out",
          name: "right_to_opt",
          widget: "boolean",
          default: false,
        }
      - {
          label: "Right to limit use",
          name: "right_to_limit",
          widget: "boolean",
          default: false,
        }
      - {
          label: "Right to Data Portability",
          name: "right_to_portability",
          widget: "boolean",
          default: false,
        }
      - {
          label: "Right to appeal",
          name: "right_to_appeal",
          widget: "boolean",
          default: false,
        }
